name: Deploy to dipapp.nl

on: push

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Upload to FTP
      uses: sebastianpopp/git-ftp-action@releases/v3
      with:
        url: "ftp://dipapq.ssh.transip.me/www/wp-content/themes/sierra-child/hkb-templates/"
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}

