name: Deploy to dipapp.nl

on:
  push:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Upload to FTP
      uses: sebastianpopp/ftp-action@v3
      with:
        host: ${{ secrets.FTP_SERVER }}
        user: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        localDir: "./"
        remoteDir: "www/wp-content/themes/sierra-child/hkb-templates"
